[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "pytorch-conda-forge"
platforms = ["linux-64"]

[feature.gpu.system-requirements]
cuda = "12.0"

[feature.gpu.dependencies]
cuda-version = "12.*"
pytorch-gpu = "*"

[feature.cpu.dependencies]
pytorch-cpu = "*"

[feature.lab.dependencies]
jupyterlab = ">=4.4.2,<5"
notebook = ">=7.4.2,<8"

[environments]
cpu = ["cpu"]
default = ["gpu"]
dev = ["cpu", "lab"]

[dependencies]
einops = ">=0.8.0,<0.9"
numpy = "<2.0"
python = ">=3.12"
omegaconf = ">=2.3.0,<3"
tqdm = ">=4.67.1,<5"
safetensors = ">=0.5.3,<0.6"
torchvision = ">=0.21.0,<0.22"
h5py = ">=3.13.0,<4"
wandb = ">=0.19.10,<0.20"
gradio = "<5"
pydantic = "==2.10.6"
pytorch-msssim = ">=1.0.0,<2"
rawpy = ">=0.25.0,<0.26"
transformers = ">=4.51.3,<5"
kornia = ">=0.8.1,<0.9"
scipy = "<1.15"

[pypi-dependencies]
clean-fid = ">=0.1.35, <0.2"
